### ISSUE TITLE
Ernten/neu pflanzen funktioniert nicht + diverse bugs/crashes

### ISSUE THREAD

**Issue by Joly0** [MasterZydra/WurzelimperiumBot#67]
Hey, ich habe mir die windows exe geladen und ausgeführt mit dem command ".\WurzelimperiumBot_1.1.0_CLI.exe.exe 29 Username XYZ123 de" da bekomme ich aber nur diese fehlermeldung:
```
Traceback (most recent call last):
  File "automated_script.py", line 27, in <module>
  File "src\WurzelBot.py", line 148, in launchBot
  File "src\Produktdaten.py", line 93, in initAllProducts
KeyError: 'sx'
[29864] Failed to execute script 'automated_script' due to unhandled exception!
```

Ohne den "de" parameter bekomme ich diese fehlermeldung:
```
An error occured while starting Wurzelbot.
Remove weed from all gardens...
Could not harvest gardens.
Watering all plants...
Claiming daily login bonus...
Traceback (most recent call last):
  File "httplib2\__init__.py", line 1343, in _conn_request
  File "httplib2\__init__.py", line 1004, in connect
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "automated_script.py", line 58, in <module>
  File "src\WurzelBot.py", line 443, in getDailyLoginBonus
  File "src\Bonus.py", line 9, in getDailyLoginBonus
  File "src\HTTPCommunication.py", line 560, in readUserDataFromServer
  File "httplib2\__init__.py", line 1701, in request
  File "httplib2\__init__.py", line 1421, in _request
  File "httplib2\__init__.py", line 1350, in _conn_request
httplib2.error.ServerNotFoundError: Unable to find the server at snonenoneajax
[29780] Failed to execute script 'automated_script' due to unhandled exception!
```
und passiert ist nichts.

Ich habe gerade erst angefangen und mein feld ist daher das normale starter-feld mit karotte und salat.

**Comment by Joly0** [comment]
Auch wenn ich mir ein virutelles env erstelle und diesen command "python.exe .\console.py" oder ".\automated_script.py 29 Username XYZ123 de" kommt nur diese meldung:
```
  _      __                 _____       __
 | | /| / /_ _________ ___ / / _ )___  / /_
 | |/ |/ / // / __/_ // -_) / _  / _ \/ __/
 |__/|__/\_,_/_/  /__/\__/_/____/\___/\__/

Initialisiere WurzelBot...
Anzahl der Gärten konnte nicht ermittelt werden.
```

und danach nichts mehr

**Comment by MasterZydra** [comment]
Hi @Joly0,
Die Windows.exe ist schon seit über einem Jahr nicht mehr aktualisiert worden.
Wenn du auf einem aktuellen Stand bleiben möchtest, würde ich dir die Python-Version empfehlen.
Die Sprache muss man mittlerweile mitgeben, damit die korrekte URL genutzt wird.

**Comment by Joly0** [comment]
Ja, ich habe gemerkt, dass die exe etwas veraltet ist, aber auch mit der python version gibt es probleme wie man in meinem letzten kommentar sieht

**Comment by MasterZydra** [comment]
Ich habe mal eine [Konfigurationsklasse](https://github.com/MasterZydra/WurzelimperiumBot/blob/933fe5d738643b21a702f6336d40fd80c6dffeee/src/core/Config.py#L9C5-L9C22) hinzugefügt. Wenn du dort den Wert von "isDebugMode" auf "True" setzt, wird die die Fehlermeldung im Detail angezeigt. Kannst du diese dann hier rein posten?

**Comment by MasterZydra** [comment]
Bei mir lokal (Linux) und in der GitHub Action (auch Linux) geht es ohne Fehler.

**Comment by Joly0** [comment]
> @Joly0 Ich habe mal eine [Konfigurationsklasse](https://github.com/MasterZydra/WurzelimperiumBot/blob/933fe5d738643b21a702f6336d40fd80c6dffeee/src/core/Config.py#L9C5-L9C22) hinzugefügt. Wenn du dort den Wert von "isDebugMode" auf "True" setzt, wird dir die Fehlermeldung im Detail angezeigt. Kannst du diese dann hier rein posten?

```
Traceback (most recent call last):
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\automated_script.py", line 28, in <module>
    succ = wurzelBot.launchBot(args.server, args.user, args.password, args.lang, args.portalacc)
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\src\WurzelBot.py", line 183, in launchBot
    raise e
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\src\WurzelBot.py", line 180, in launchBot
    self.__initGardens()
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\src\WurzelBot.py", line 77, in __initGardens
    self.park = Park(self.__HTTPConn)
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\src\Stadtpark.py", line 13, in __init__
    self.__setParkData(self._httpConn.initPark())
  File "C:\Users\julian\Downloads\WurzelimperiumBot-master\WurzelimperiumBot-master\src\Stadtpark.py", line 18, in __setParkData
    self._cashpoint = jContent["data"]["data"]["cashpoint"]
TypeError: 'int' object is not subscriptable
```

**Comment by Joly0** [comment]
Das ist die fehlermeldung die ich bekomme

**Comment by MasterZydra** [comment]
@Joly0 Danke. Ich konnte den Fehler finden und beheben. Der Stadtpark ist ab Level 5 verfügbar. 
https://github.com/MasterZydra/WurzelimperiumBot/commit/701c38341230cd4cfa5add8010ac11a9361c711c

**Comment by Joly0** [comment]
Danke dir, ich werde es später testen und dir bescheid geben, ob es soweit funktioniert

**Comment by Joly0** [comment]
Ok, ich kann bestätigen, dass das problem gelöst wurde und soweit alles läuft:

```
python.exe .\automated_script.py 29 username passwort de
Entferne Unkraut aus allen Gärten...
Feld 6 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 12 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 13 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 14 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 15 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 16 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 17 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 26 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 27 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 28 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 29 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 30 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 31 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 43 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 47 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 48 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 51 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 60 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 61 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 62 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 63 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 64 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 66 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 67 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 68 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 79 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 80 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 82 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 85 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 97 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 98 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 101 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 102 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 113 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 114 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 116 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 118 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 119 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 130 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 132 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 134 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 136 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 150 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 152 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 153 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 165 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 166 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 167 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 168 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 183 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 184 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 199 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 1 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 3 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 4 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 5 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 7 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 10 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 11 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 22 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 23 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 25 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 32 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 35 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 42 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 44 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 45 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 46 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 49 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 50 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 65 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 69 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 81 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 83 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 94 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 99 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 103 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 111 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 115 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 120 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 128 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 131 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 135 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 137 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 149 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 151 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 161 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 169 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 170 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 178 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 180 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 181 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 182 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 185 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 186 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 187 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 188 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 200 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 204 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 8 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 9 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 24 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 33 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 34 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 59 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 77 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 84 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 96 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 100 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 110 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 112 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 117 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 133 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 147 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 154 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 164 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 171 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 196 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 198 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 201 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 202 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 203 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 148 im Garten 1 konnte nicht von Unkraut befreit werden!
Feld 163 im Garten 1 konnte nicht von Unkraut befreit werden!
Es wurden geerntet:
120x Erdbeere

120x Tomate

40x Karotte
Gurke anpflanzen...
Im Garten 1 wurden 80 Pflanzen gepflanzt.
Alle Pflanzen gießen...
Im Garten 1 wurden 80 Pflanzen gegossen.
Täglicher Login Bonus abholen...
Bediene Wimps in Gärten...
Selling products to wimp: 42663520
Price: 8.67 wT
34x Gurke
56x Salat
48x Karotte
Selling products to wimp: 42664971
Price: 14.35 wT
40x Tomate
```

**Comment by xRuffKez** [comment]
@Joly0 
Hab eine neue Version Released:
https://github.com/MasterZydra/WurzelimperiumBot/releases/tag/v27.02.24.05.26
